version: '2.1'
orbs:
  java-maven: whoop/java-maven@1.0
jobs:
  build:
    executor:
      name: java-maven/java11
    resource_class: xlarge
    steps:
      - checkout
      - java-maven/resolve-dependencies
      - java-maven/build-and-test
      - java-maven/sonarqube
      - java-maven/publish
workflows:
  build_and_test:
    jobs:
      - build:
          context: environment-variables
      - java-maven/snyk_security_scan:
          context: environment-variables
  version: 2
