version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        parallelism: 4
    steps:
      - checkout
      - run : mvn test package
      - store_artifacts:
          path:  target

